// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package dog

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DogServiceClient is the client API for DogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DogServiceClient interface {
	GetDog(ctx context.Context, in *DogRequest, opts ...grpc.CallOption) (*DogResponse, error)
}

type dogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDogServiceClient(cc grpc.ClientConnInterface) DogServiceClient {
	return &dogServiceClient{cc}
}

func (c *dogServiceClient) GetDog(ctx context.Context, in *DogRequest, opts ...grpc.CallOption) (*DogResponse, error) {
	out := new(DogResponse)
	err := c.cc.Invoke(ctx, "/dog.DogService/GetDog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DogServiceServer is the server API for DogService service.
// All implementations must embed UnimplementedDogServiceServer
// for forward compatibility
type DogServiceServer interface {
	GetDog(context.Context, *DogRequest) (*DogResponse, error)
	mustEmbedUnimplementedDogServiceServer()
}

// UnimplementedDogServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDogServiceServer struct {
}

func (UnimplementedDogServiceServer) GetDog(context.Context, *DogRequest) (*DogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDog not implemented")
}
func (UnimplementedDogServiceServer) mustEmbedUnimplementedDogServiceServer() {}

// UnsafeDogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DogServiceServer will
// result in compilation errors.
type UnsafeDogServiceServer interface {
	mustEmbedUnimplementedDogServiceServer()
}

func RegisterDogServiceServer(s grpc.ServiceRegistrar, srv DogServiceServer) {
	s.RegisterService(&DogService_ServiceDesc, srv)
}

func _DogService_GetDog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DogServiceServer).GetDog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dog.DogService/GetDog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DogServiceServer).GetDog(ctx, req.(*DogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DogService_ServiceDesc is the grpc.ServiceDesc for DogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dog.DogService",
	HandlerType: (*DogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDog",
			Handler:    _DogService_GetDog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dog.proto",
}
